In [2]:
from statsbombpy import sb

In [3]:
sb.competitions()

c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2026-04-11T12:48:10.012987,2021-06-13T16:17:31.694,None,2026-04-11T12:48:10.012987
76,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2026-04-27T22:02:42.690507,2026-04-27T22:03:28.087062,2026-04-27T22:03:28.087062,2026-04-27T22:02:42.690507
77,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2026-05-05T03:03:04.199896,2026-05-05T03:05:32.480837,2026-05-05T03:05:32.480837,2026-05-05T03:03:04.199896
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,None,2026-05-15T15:31:40.299642

In [13]:
sb.matches(competition_id = 43, season_id = 106)

c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3857276,2022-12-01,15:00:00.000,1,2,available,available,2026-05-04T01:46:04.664252,2026-05-04T01:50:33.318123,3,...,England,1000518,Walid Regragui,None,1975-09-23,154,Morocco,1.1.0,2,2
1,3857271,2022-11-21,13:00:00.000,6,2,available,available,2026-05-04T01:40:47.671394,2026-05-04T01:43:30.216315,1,...,England,645,Carlos Manuel Brito Leal Queiróz,Carlos Queiroz,1953-03-01,183,Portugal,1.1.0,2,2
2,3857296,2022-12-01,15:00:00.000,0,0,available,available,2026-05-04T01:44:02.255386,2026-05-04T01:50:06.343225,3,...,Croatia,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2
3,3857274,2022-11-25,16:00:00.000,1,1,available,available,2026-05-04T01:43:00.444702,2026-05-04T01:50:07.646458,2,...,Netherlands,2881,Gustavo Julio Alfaro,Gustavo Alfaro,1962-08-14,11,Argentina,1.1.0,2,2
4,3857255,2022-12-01,19:00:00.000,2,1,available,available,2026-05-04T01:42:55.630428,2026-05-04T01:49:36.594944,3,...,Japan,793,Luis Enrique Martínez García,Luis Enrique,1970-05-08,214,Spain,1.1.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,3857291,2022-11-23,16:00:00.000,7,0,available,available,2026-05-03T16:08:38.580488,2026-05-03T16:12:13.412295,1,...,Spain,3094,Luis Fernando Suárez Guzman,Luis Fernando Suárez,1959-12-23,49,Colombia,1.1.0,2,2
60,3857281,2022-11-27,16:00:00.000,4,1,available,available,2026-05-04T01:47:00.853566,2026-05-04T01:51:52.104873,2,...,Croatia,4435,John Herdman,None,1975-07-19,68,England,1.1.0,2,2
61,3857280,2022-12-02,19:00:00.000,1,0,available,available,2026-05-03T15:41:58.839286,2026-05-03T15:44:07.018244,3,...,Cameroon,547,Adenor Leonardo Bacchi,Tite,1961-05-25,31,Brazil,1.1.0,2,2
62,3857279,2022-11-22,19:00:00.000,4,1,available,available,2026-05-04T01:44:53.405576,2026-05-04T01:50:33.615237,1,...,France,5696,Graham James Arnold,None,1963-08-03,14,Australia,1.1.0,2,2
63,3857262,2022-12-02,15:00:00.000,2,1,available,available,2026-05-03T16:05:21.572751,2026-05-03T16:07:48.636747,3,...,Portugal,607,Fernando Manuel Fernandes da Costa Santos,Fernando Santos,1954-10-10,183,Portugal,1.1.0,2,2

In [5]:
sb.events(match_id = 3923881).head(10)

c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 343, 'lineup': [{'player': {'id'...",Nigeria,775,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Côte d'Ivoire,3374,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Côte d'Ivoire,3374,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Côte d'Ivoire,3374,00:00:00.000,Half Start,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:00.000,Half Start,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:00.663,Pass,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:03.081,Pass,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:06.561,Pass,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:09.250,Pass,True

In [14]:
all_matches = []

for match_id in sb.matches(competition_id = 43, season_id = 106).match_id:
    temp_match = sb.events(match_id = match_id)
    all_matches.append(temp_match)

c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\pawan\anaconda34\envs\dataAnalysisPython\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [20]:
import pandas as pd
df = pd.concat(all_matches)

In [16]:
df.player.unique()

array([nan, 'Youssef En-Nesyri', 'Sofyan Amrabat', 'Nayef Aguerd',
       'Romain Saïss', 'Achraf Hakimi Mouh', 'Hakim Ziyech',
       'Yassine Bounou', 'Abdelhamid Sabiri', 'Sofiane Boufal',
       'Noussair Mazraoui', 'Milan Borjan', 'Kamal Miller',
       'David Junior Hoilett', 'Cyle Larin', 'Alphonso Davies',
       'Steven de Sousa Vitoria', 'Azzedine Ounahi', 'Alistair Johnston',
       'Jonathan Osorio', 'Mark Anthony Kaye', 'Sam Adekugbe',
       'Tajon Buchanan', 'Atiba Hutchinson', 'Ismael Koné',
       'Jonathan David', 'Zakaria Aboukhlal', 'Richie Laryea',
       'Selim Amallah', 'David Wallace Wotherspoon',
       'Abderrazak Hamdallah', 'Jawad El Yamiq', 'Yahya Jabrane',
       'Alireza Jahanbakhsh', 'Morteza Pouraliganji', 'Mehdi Taremi',
       'Kieran Trippier', 'John Stones', 'Luke Shaw', 'Harry Maguire',
       'Jude Bellingham', 'Declan Rice', 'Mason Mount', 'Bukayo Saka',
       'Alireza Safar Beiranvand', 'Roozbeh Cheshmi', 'Raheem Sterling',
       'Seyed Majid Hosseini', 'Harry Kane', 'Jordan Pickford',
       'Ehsan Hajsafi', 'Ali Karimi', 'Milad Mohammadi',
       'Ahmad Nourollahi', 'Sadegh Moharrami', 'Seyed Hossein Hosseini',
       'Saeid Ezatolahi Afagh', 'Mohammad Hossein Kanani Zadegan',
       'Ali Gholizadeh', 'Mehdi Torabi', 'Eric Dier', 'Phil Foden',
       'Jack Grealish', 'Marcus Rashford', 'Callum Wilson',
       'Sardar Azmoun', 'Mateo Kovačić', 'Marcelo Brozović',
       'Luka Modrić', 'Thibaut Courtois', 'Josip Juranović',
       'Dejan Lovren', 'Dominik Livaković', 'Borna Sosa', 'Ivan Perišić',
       'Marko Livaja', 'Andrej Kramarić', 'Yannick Ferreira Carrasco',
       'Dries Mertens', 'Timothy Castagne', 'Axel Witsel',
       'Leandro Trossard', 'Thomas Meunier', 'Kevin De Bruyne',
       'Toby Alderweireld', 'Jan Vertonghen', 'Leander Dendoncker',
       'Joško Gvardiol', 'Romelu Lukaku Menama', 'Thorgan Hazard',
       'Bruno Petković', 'Mario Pašalić', 'Youri Tielemans',
       'Jeremy Doku', 'Eden Hazard', 'Lovro Majer',
       'Gonzalo Jordy Plata Jiménez', 'Piero Martín Hincapié Reyna',
       'Denzel Dumfries', 'Davy Klaassen', 'Felix Eduardo Torres Caicedo',
       'Angelo Smit Preciado Quiñónez', 'Nathan Aké',
       'Michael Steveen Estrada Martínez', 'Jurriën David Norman Timber',
       'Teun Koopmeiners', 'Frenkie de Jong', 'Daley Blind',
       'Virgil van Dijk', 'Cody Mathès Gakpo',
       'Pervis Josué Estupiñán Tenorio', 'Moisés Isaac Caicedo Corozo',
       'Hernán Ismael Galíndez', 'Jackson Gabriel Porozo Vernaza',
       'Steven Bergwijn', 'Jhegson Sebastián Méndez Carabalí',
       'Enner Remberto Valencia Lastra', 'Andries Noppert',
       'Memphis Depay', 'Steven Berghuis',
       'Jeremy Leonel Sarmiento Morante', 'Wout Weghorst',
       'Marten de Roon', 'Romario Andrés Ibarra Mina',
       'Kevin José Rodríguez Cortez', 'Pablo Martín Páez Gavira',
       'Pau Francisco Torres', 'César Azpilicueta Tanco',
       'Rodrigo Hernández Cascante', 'Pedro González López',
       'Sergio Busquets i Burgos', 'Álvaro Borja Morata Martín',
       'Alejandro Balde Martínez', 'Nicholas Williams Arthuer',
       'Junya Ito', 'Takefusa Kubo', 'Daniel Olmo Carvajal',
       'Hidemasa Morita', 'Daichi Kamada', 'Ao Tanaka',
       'Unai Simón Mendibil', 'Ko Itakura', 'Maya Yoshida',
       'Yuto Nagatomo', 'Shogo Taniguchi', 'Shūichi Gonda',
       'Daizen Maeda', 'Kaoru Mitoma', 'Ritsu Doan',
       'Daniel Carvajal Ramos', 'Ferrán Torres García', 'Takuma Asano',
       'Marco Asensio Willemsen', 'Takehiro Tomiyasu', 'Jordi Alba Ramos',
       'Anssumane Fati', 'Wataru Endo', 'Walker Zimmerman',
       'Matthew Charles Turner', 'Tyler Adams', 'Haji Wright',
       'Timothy Weah', 'Weston McKennie', 'Tim Ream', 'Sergino Dest',
       'Christian Pulisic', 'Yunus Dimoara Musah', 'Antonee Robinson',
       'Jordan Brian Henderson', 'Shaquell Moore', 'Brenden Aaronson',
       'Joshua Sargent', 'Giovanni Reyna', 'Ramin Rezaeian',
       'Cameron Carter-Vickers', 'Saman Ghoddos',
       'Kellyn Kai Perry-Acosta', 'Abolfazl Jalali', 'Karim Ansarifard',
       'Nikola Vlašić', 'Yahia Attiyat allah', 'Abdessamad Ezzalzouli',
       'Mislav Oršić', 'Aaron Ramsey', 'Chris Mepham', 'Joe Rodon',
       'Ethan Ampadu', 'Ben Davies', 'Connor Roberts', 'Wayne Hennessey',
       'Neco Williams', 'Kieffer Roberto Francisco Moore', 'Harry Wilson',
       'Gareth Frank Bale', 'Daniel James', 'Brennan Johnson',
       'Joe Allen', 'Daniel Ward', 'Ellyes Joris Skhiri', 'Wahbi Khazri',
       'Anis Ben Slimane', 'Wajdi Kechrida', 'Yassine Meriah',
       'Nader Ghandri', 'Montassar Omar Talbi', 'Ali Maâloul',
       'Steve Mandanda', 'Raphaël Varane', 'Axel Disasi',
       'Aïssa Bilal Laïdouni', 'Aymen Dahmen', 'Ibrahima Konaté',
       'Eduardo Camavinga', 'Mohamed Ali Ben Romdhane', 'Kingsley Coman',
       'Aurélien Djani Tchouaméni', 'Jordan Veretout', 'Youssouf Fofana',
       'Randal Kolo Muani', 'Mattéo Guendouzi Olié', 'William Saliba',
       'Issam Jebali', 'Adrien Rabiot', 'Kylian Mbappé Lottin',
       'Antoine Griezmann', 'Ousmane Dembélé', 'Ghilane Chalali',
       'Ali Abdi', 'Kyle Walker', 'Joseff Morrell',
       'Trent Alexander-Arnold', 'Kalvin Phillips', 'Rubin Colwill',
       'Xherdan Shaqiri', 'Manuel Obafemi Akanji',
       'Ngoran Suiru Fai Collins', 'Bryan Mbeumo', 'Granit Xhaka',
       'Nico Elvedi', "Nicolas Alexis Julio N'Koulou Ndoubena",
       'Samuel Yves Oum Gwet', 'Djibril Sow', 'Martin Hongla Yma II',
       'Ricardo Iván Rodríguez Araya', 'Remo Freuler', 'Silvan Widmer',
       'André-Frank Zambo Anguissa', 'André Onana', 'Ruben Vargas',
       'Breel-Donald Embolo', 'Nouhou Tolo', 'Karl Brillant Toko Ekambi',
       'Jean-Charles Castelletto', 'Yann Sommer',
       'Jean-Eric Maxim Choupo-Moting', 'Gaël Ondoua',
       'Georges-Kévin Nkoudou Mbida', 'Vincent Paté Aboubakar',
       'Fabian Frei', 'Haris Seferović', 'Fabian Rieder', 'Noah Okafor',
       'Nicolas Moumi Ngamaleu', 'Eray Ervin Cömert',
       'Cristiano Ronaldo dos Santos Aveiro',
       'Bernardo Mota Veiga de Carvalho e Silva',
       'Rúben Diogo Da Silva Neves', 'Rúben Santos Gato Alves Dias',
       'João Pedro Cavaco Cancelo', 'Danilo Luís Hélio Pereira',
       'Raphaël Adelino José Guerreiro', 'João Félix Sequeira',
       'Diogo Meireles Costa', 'Otávio Edmilson da Silva Monteiro',
       'Mohamed Salisu', 'Abdul Rahman Baba', 'Alexander Djiku',
       'Lawrence Ati-Zigi', 'Daniel Amartey', 'André Ayew Pelé',
       'Alidu Seidu', 'Thomas Teye Partey',
       'Bruno Miguel Borges Fernandes', 'Iñaki Williams Arthuer',
       'Salis Abdul Samed', 'Mohammed Kudus', 'William Silva de Carvalho',
       'Tariq Lamptey', 'Jordan Ayew', 'Osman Bukari',
       'Rafael Alexandre Conceição Leão',
       'João Maria Lobo Alves Palhinha Gonçalves', 'Gonçalo Matias Ramos',
       'João Mário Naval da Costa Eduardo', 'Daniel-Kofi Kyereh',
       'Antoine Semenyo', 'Vincent Janssen', 'Ismaïla Sarr',
       'Idrissa Gana Gueye', 'Youssouf Sabaly', 'Nampalys Mendy',
       'Krépin Diatta', 'Abdou Diallo', 'Matthijs de Ligt',
       'Kalidou Koulibaly', 'Cheikhou Kouyaté', 'Boulaye Dia',
       'Pape Abou Cissé', 'Edouard Mendy', 'Ismail Jakobs', 'Pape Gueye',
       'Nicolas Jackson', 'Cheikh Ahmadou Bamba Mbacke Dieng',
       'DeAndre Yedlin', 'Jordan Morris', 'Sorba Thomas',
       'Piotr Zieliński', 'Jakub Piotr Kiwior', 'Mohammed Al Burayk',
       'Ali Albulayhi', 'Salem Mohammed Al Dawsari', 'Mohammed Kanoo',
       'Przemysław Frankowski', 'Abdulelah Al Amri',
       'Saud Abdullah Abdul Hamid', 'Mohammed Khalil Al Owais',
       'Abdulelah Saad Hameed Al-Malki', 'Krystian Bielik',
       'Wojciech Szczęsny', 'Matty Cash', 'Robert Lewandowski',
       'Bartosz Bereszyński', 'Saleh Khalid Al Shehri', 'Kamil Glik',
       'Sami Khalil Al Naji', 'Arkadiusz Milik',
       'Firas Tariq Nasser Al Albirakan', 'Grzegorz Krychowiak',
       'Nawaf Shaker Al Abid', 'Jakub Kamiński',
       'Sultan Abdullah Salim Al Ghannam', 'Krzysztof Piątek',
       'Abdulrahman Al-Obood', 'Nasser Al Dawsari', 'Hattan Babhir',
       'Meshaal Aissa Barsham', 'Boualem Khoukhi', 'Pedro Miguel Correia',
       'Abdelkarim Hassan Al Haj Fadlalla', 'Ismaeel Mohammad Mohammad',
       'Assim Omer Al Haj Madibo', 'Akram Hassan Afif',
       'Hassan Khalid Al Heidos', 'Homam Alamin Ahmed',
       'Abdulaziz Hatem Mohammed Abdullah',
       'Almoez Ali Zainalabiddin Abdulla', 'Karim Boudiaf',
       'Mohammed Muntari', 'Ali Assadalla Thaimn Qambar',
       'Mosaab Khoder Jibril', 'Kenneth Taylor',
       'Ahmed Alaa Eldin Abdelmotaal', 'Andreas Evald Cornelius',
       'Christian Dannemann Eriksen', 'Rasmus Nissen Kristensen',
       'Jesper Lindstrøm', 'Pierre-Emile Højbjerg', 'Joakim Mæhle',
       'Victor Nelsson', 'Andreas Christensen', 'Kasper Schmeichel',
       'Joachim Andersen', 'Jules Koundé', 'Mikkel Damsgaard',
       'Hugo Lloris', 'Dayotchanculle Upamecano',
       'Theo Bernard François Hernández', 'Olivier Giroud',
       'Martin Braithwaite Christensen', 'Marcus Thuram',
       'Kasper Dolberg', 'Christian Nørgaard', 'Alexander Hartmann Bah',
       'Kai Havertz', 'Joshua Kimmich', 'Manuel Neuer',
       'Nico Schlotterbeck', 'Antonio Rüdiger', 'Niklas Süle',
       'David Raum', 'Jamal Musiala', 'Serge Gnabry', 'Thomas Müller',
       'Hiroki Sakai', 'İlkay Gündoğan', 'Jonas Hofmann', 'Leon Goretzka',
       'Takumi Minamino', 'Mario Götze', 'Niclas Füllkrug',
       'Youssoufa Moukoko', 'Andreas Skov Olsen',
       'Dylan Daniel Mahmoud Bronn', 'Simon Thorup Kjær',
       'Thomas Delaney', 'Mohamed Dräger', 'Youssef Msakni',
       'Mathias Jensen', 'Naïm Sliti', 'Hannibal Mejbri',
       'Taha Yassine Khenissi', 'Ferjani Sassi', 'Henry Josué Martín Mex',
       'Héctor Miguel Herrera López', 'Luis Gerardo Chávez Magallón',
       'Jesús Daniel Gallardo Vasconcelos',
       'Héctor Alfredo Moreno Herrera',
       'Francisco Guillermo Ochoa Magaña', 'Sebastian Szymański',
       'Ernesto Alexis Vega Rojas', 'Edson Omar Álvarez Velázquez',
       'César Jasib Montes Castro', 'Jorge Eduardo Sánchez Ramos',
       'Hirving Rodrigo Lozano Bahena', 'Nicola Zalewski',
       'Carlos Alberto Rodríguez Gómez', 'Raúl Alonso Jiménez Rodríguez',
       'Carlos Uriel Antuna Romero', 'Famara Diedhiou',
       'Pathé Ismaël Ciss', 'Iliman Ndiaye', 'Pape Matar Sarr',
       'Tarek Salman Salman', 'Mohammed Waed Abdulwahhab Al Bayati',
       'Stephen Antunes Eustáquio', 'Michy Batshuayi Tunga',
       'Amadou Onana', 'Ikoma Loïs Openda', 'Liam Millar',
       'Marcos Aoás Corrêa', 'Carlos Henrique Casimiro',
       'Lucas Tolentino Coelho de Lima', 'Alex Sandro Lobo Silva',
       'Thiago Emiliano da Silva', 'Éder Gabriel Militão',
       'Alisson Ramsés Becker', 'Raphael Dias Belloli',
       'Richarlison de Andrade', 'Frederico Rodrigues Santos',
       'Vinícius José Paixão de Oliveira Júnior', 'Rodrygo Silva de Goes',
       'Edimilson Fernandes', 'Renato Steffen',
       'Bruno Guimarães Rodriguez Moura', 'Antony Matheus dos Santos',
       'Michel Aebischer', 'Gabriel Fernando de Jesus',
       'Alex Nicolao Telles', 'Enzo Fernandez', 'Nicolás Hernán Otamendi',
       'Cristian Gabriel Romero', 'Nahuel Molina Lucero',
       'Rodrigo Javier De Paul', 'Alexis Mac Allister',
       'Marcos Javier Acuña', 'Lisandro Martínez',
       'Lionel Andrés Messi Cuccittini', 'Julián Álvarez',
       'Damián Emiliano Martínez', 'Leandro Daniel Paredes',
       'Germán Alejandro Pezzella', 'Lautaro Javier Martínez',
       'Luuk de Jong', 'Nicolás Alejandro Tagliafico',
       'Gonzalo Ariel Montiel', 'Ángel Fabián Di María Hernández',
       'Noa Lang', 'Brandon Aguilera Zamora', 'Keylor Navas Gamboa',
       'Celso Borges Mora', 'Keysher Fuller Spence',
       'Joel Nathaniel Campbell Samuels', 'Juan Pablo Vargas Campos',
       'Leroy Sané', 'Óscar Esau Duarte Gaitán',
       'Kendall Jamaal Waston Manley', 'Johan Alberto Venegas Ulloa',
       'Yeltsin Ignacio Tejeda Valverde', 'Bryan Oviedo',
       'Lukas Klostermann', 'Youstin Delfin Salas Gómez',
       'Ronald Alberto Matarrita Ulate', 'Jewison Bennette',
       'Roan Roberto Wilson Gordon', 'Anthony Daniel Contreras Enríquez',
       'Matthias Ginter', 'Francisco Javier Calvo Quesada', 'Ayase Ueda',
       'Yuki Soma', 'Miki Yamane', 'Gerson Torres Barrantes',
       'Hiroki Ito', 'Daniel Alonso Chacón Salas',
       'Paulo Bruno Exequiel Dybala', 'Josip Stanišić', 'Josip Šutalo',
       'Achraf Dari', 'Bilal El Khannous', 'Ilias Chair', 'Badr Banoun',
       'Anass Zaroury', 'Fabian Lukas Schär', 'Andrija Živković',
       'Saša Lukić', 'Gregor Kobel', 'Nikola Milenković',
       'Sergej Milinković-Savić', 'Filip Kostić', 'Strahinja Pavlović',
       'Milos Veljkovic', 'Vanja Milinković Savić', 'Dušan Tadić',
       'Aleksandar Mitrović', 'Dušan Vlahović', 'Nemanja Gudelj',
       'Luka Jović', 'Nemanja Maksimović', 'Denis Lemi Zakaria Lako Lado',
       'Christian Fassnacht', 'Nemanja Radonjić', 'Filip Đuričić',
       'Predrag Rajković', 'Jackson Irvine', 'Kye Rowles',
       'Mathew Leckie', 'Mitchell Thomas Duke', 'Miloš Degenek',
       'Alejandro Darío Gómez', 'Aziz Eraltay Behich', 'Harry Souttar',
       'Mathew Ryan', 'Aaron Mooy', 'Riley McGree', 'Keanu Baccus',
       'Craig Goodwin', 'Ajdin Hrustic', 'Fran Karačić', 'Jamie MacLaren',
       'Exequiel Alejandro Palacios', 'Garang Kuol', 'Robert Skov',
       'Bailey Wright', 'Neymar da Silva Santos Junior',
       'Danilo Luiz da Silva', 'Filip Mladenović', 'Ivan Ilić',
       'Darko Lazović', 'Gabriel Teodoro Martinelli Silva',
       'Awer Denis Bul Mabil', 'Alan Steven Franco Palma',
       'Carlos Armando Gruezo Arboleda', 'José Adoni Cifuentes Charcopa',
       'Djorkaeff Neicer Reasco González', 'Ui-Jo Hwang',
       'Woo-Young Jung', 'Young-Gwon Kim', 'Matías Vecino Falero',
       'Rodrigo Bentancur Colmán', 'Mathías Olivera Miramontes',
       'Darwin Gabriel Núñez Ribeiro', 'Min Jae Kim', 'Heung-Min Son',
       'Sergio Rochet Álvarez', 'Seung-Gyu Kim',
       'José Martín Cáceres Silva', 'Jae-Sung Lee', 'Jin-Su Kim',
       'In-Beom Hwang', 'Luis Alberto Suárez Díaz', 'Moon-Hwan Kim',
       'Diego Roberto Godín Leal', 'José María Giménez de Vargas',
       'Sang-Ho Na', 'Federico Santiago Valverde Dipetta',
       'Facundo Pellistri Rebollo', 'Jun-Ho Son', 'Kang-In Lee',
       'Gue-Sung Cho', 'Edinson Roberto Cavani Gómez',
       'Diego Nicolás De La Cruz Arcosa',
       'Matías Nicolás Viña Susperreguy', 'Guillermo Varela Olivera',
       'Kléper Laveran Lima Ferreira', 'José Diogo Dalot Teixeira',
       'Vitor Machado Ferreira', 'Walid Cheddira',
       'Ricardo Jorge Luz Horta', 'Orbelín Pineda Alvarado',
       'Ali Al Hassan', 'Hassan Mohammed Al-Tambakti', 'Riyadh Sharahili',
       'Abdullah Mohammed Madu', 'Kevin Nahin Álvarez Campos',
       'Rogelio Gabriel Funes Mori', 'Karol Świderski', 'Michał Skóraś',
       'Damian Szymański', 'Artur Jędrzejczyk', 'Thiago Ezequiel Almada',
       'José Andrés Guardado Hernández', 'Guido Rodríguez',
       'Néstor Alejandro Araújo Razo', 'Érick Gabriel Gutiérrez Galaviz',
       'Roberto Carlos Alvarado Hernández', 'Ardon Jashari',
       'Philip Foden', 'Fodé Ballo Touré', 'Juan Marcos Foyth',
       'Ángel Martín Correa', 'Pedro Guilherme Abreu dos Santos',
       'Ante Budimir', 'Aymeric Laporte', 'Marcos Llorente Moreno',
       'Carlos Soler Barragán', 'Pablo Sarabia García', 'Borna Barišić',
       'Hee-Chan Hwang', 'Chul Hong', 'Daniel Alves da Silva',
       'Seung-Ho Paik', 'Gleison Bremer Silva Nascimento',
       'Weverton Pereira da Silva', 'Jan Bednarek', 'Kamil Grosicki',
       'Jesus Ferreira', 'Xavi Simons', 'Nuno Mendes',
       'Sebastián Coates Nión', 'Giorgian Daniel De Arrascaeta Benedetti',
       'Maximiliano Gómez González', 'Matheus Luiz Nunes', 'Thilo Kehrer',
       'Jorge Resurrección Merodio', 'Devis Rogers Epassy Mboka',
       'Pierre Kunde Malong', 'Stefan Mitrović',
       'Christian Mougang Bassogog', 'Marko Grujić', 'Srđan Babić',
       'Munir Mohand Mohamedi', 'Charles De Ketelaere',
       'Bassam Hisham Al Rawi', 'Saad Abdullah Al Sheeb',
       'Salman Mohammed Al Faraj', 'Yasir Gharsan Al Shahrani',
       'Haitham Mohammed Asiri', 'Woo-Yeong Jeong', 'Gideon Mensah',
       'Chang-Hoon Kwon', 'Denis Odoi', 'Kamaldeen Sulemana',
       'Kyung-Won Kwon', 'Agustín Canobbio Graviz',
       'Abdul Fatawu Issahaku', 'Carlos Manuel Martínez Castro',
       'Bryan Ruiz González', 'Álvaro José Zamora Mata',
       'Lucas Daniel Cavallini', 'Fábio Henrique Tavares',
       'Ederson Santana de Moraes', 'Enzo Ebosse', 'Christopher Wooh',
       'Éverton Augusto de Barros Ribeiro', 'Jules Olivier Ntcham',
       'Jerome Ngom Mbekeli', 'Benjamin Pavard', 'Lucas Hernández Pi',
       'Nathaniel Atkinson', 'Jason Cummings',
       'António João Pereira Albuquerque Tavares Silva',
       'André Miguel Valente Silva', 'Yu-Min Cho'], dtype=object)

In [17]:
display(all_matches)

[     50_50 ball_receipt_outcome ball_recovery_recovery_failure  \
 0      NaN                  NaN                            NaN
 1      NaN                  NaN                            NaN
 2      NaN                  NaN                            NaN
 3      NaN                  NaN                            NaN
 4      NaN                  NaN                            NaN
 ...    ...                  ...                            ...
 3383   NaN                  NaN                            NaN
 3384   NaN                  NaN                            NaN
 3385   NaN                  NaN                            NaN
 3386   NaN                  NaN                            NaN
 3387   NaN                  NaN                            NaN

      block_deflection carry_end_location clearance_aerial_won  \
 0                 NaN                NaN                  NaN
 1                 NaN                NaN                  NaN
 2                 NaN                NaN                  NaN
 3                 NaN                NaN                  NaN
 4                 NaN                NaN                  NaN
 ...               ...                ...                  ...
 3383              NaN                NaN                  NaN
 3384              NaN                NaN                  NaN
 3385              NaN                NaN                  NaN
 3386              NaN                NaN                  NaN
 3387              NaN                NaN                  NaN

      clearance_body_part clearance_head clearance_left_foot clearance_other  \
 0                    NaN            NaN                 NaN             NaN
 1                    NaN            NaN                 NaN             NaN
 2                    NaN            NaN                 NaN             NaN
 3                    NaN            NaN                 NaN             NaN
 4                    NaN            NaN                 NaN             NaN
 ...                  ...            ...                 ...             ...
 3383                 NaN            NaN                 NaN             NaN
 3384                 NaN            NaN                 NaN             NaN
 3385                 NaN            NaN                 NaN             NaN
 3386                 NaN            NaN                 NaN             NaN
 3387                 NaN            NaN                 NaN             NaN

       ... substitution_outcome substitution_outcome_id  \
 0     ...                  NaN                     NaN
 1     ...                  NaN                     NaN
 2     ...                  NaN                     NaN
 3     ...                  NaN                     NaN
 4     ...                  NaN                     NaN
 ...   ...                  ...                     ...
 3383  ...             Tactical                   103.0
 3384  ...             Tactical                   103.0
 3385  ...             Tactical                   103.0
 3386  ...             Tactical                   103.0
 3387  ...             Tactical                   103.0

        substitution_replacement substitution_replacement_id  \
 0                           NaN                         NaN
 1                           NaN                         NaN
 2                           NaN                         NaN
 3                           NaN                         NaN
 4                           NaN                         NaN
 ...                         ...                         ...
 3383              Richie Laryea                     16120.0
 3384  David Wallace Wotherspoon                      9036.0
 3385       Abderrazak Hamdallah                     59493.0
 3386             Jawad El Yamiq                      7459.0
 3387              Yahya Jabrane                    102668.0

                                                 tactics     team team_id  \
 0     {'formation': 4411, 'lineup': [{'player': {'id...   Canada    1833
 1     {'formation': 433, 'lineup': [{'player': {'id'...  Morocco     788
 2                                                   NaN  Morocco     788
 3                                                   NaN   Canada    1833
 4                                                   NaN  Morocco     788
 ...                                                 ...      ...     ...
 3383                                                NaN   Canada    1833
 3384                                                NaN   Canada    1833
 3385                                                NaN  Morocco     788
 3386                                                NaN  Morocco     788
 3387                                                NaN  Morocco     788

          timestamp          type under_pressure
 0     00:00:00.000   Starting XI            NaN
 1     00:00:00.000   Starting XI            NaN
 2     00:00:00.000    Half Start            NaN
 3     00:00:00.000    Half Start            NaN
 4     00:00:00.000    Half Start            NaN
 ...            ...           ...            ...
 3383  00:20:04.889  Substitution            NaN
 3384  00:30:24.705  Substitution            NaN
 3385  00:30:36.921  Substitution            NaN
 3386  00:30:48.383  Substitution            NaN
 3387  00:39:55.443  Substitution            NaN

 [3388 rows x 91 columns],
      ball_receipt_outcome ball_recovery_recovery_failure block_deflection  \
 0                     NaN                            NaN              NaN
 1                     NaN                            NaN              NaN
 2                     NaN                            NaN              NaN
 3                     NaN                            NaN              NaN
 4                     NaN                            NaN              NaN
 ...                   ...                            ...              ...
 3644                  NaN                            NaN              NaN
 3645                  NaN                            NaN              NaN
 3646                  NaN                            NaN              NaN
 3647                  NaN                            NaN              NaN
 3648                  NaN                            NaN              NaN

      block_offensive carry_end_location clearance_aerial_won  \
 0                NaN                NaN                  NaN
 1                NaN                NaN                  NaN
 2                NaN                NaN                  NaN
 3                NaN                NaN                  NaN
 4                NaN                NaN                  NaN
 ...              ...                ...                  ...
 3644             NaN                NaN                  NaN
 3645             NaN                NaN                  NaN
 3646             NaN                NaN                  NaN
 3647             NaN                NaN                  NaN
 3648             NaN                NaN                  NaN

      clearance_body_part clearance_head clearance_left_foot  \
 0                    NaN            NaN                 NaN
 1                    NaN            NaN                 NaN
 2                    NaN            NaN                 NaN
 3                    NaN            NaN                 NaN
 4                    NaN            NaN                 NaN
 ...                  ...            ...                 ...
 3644                 NaN            NaN                 NaN
 3645                 NaN            NaN                 NaN
 3646                 NaN            NaN                 NaN
 3647                 NaN            NaN                 NaN
 3648                 NaN            NaN                 NaN

      clearance_right_foot  ... substitution_outcome substitution_outcome_id  \
 0                     NaN  ...                  NaN                     NaN
 1                     NaN  ...                  NaN                     NaN
 2                     NaN  ...                  NaN                     NaN
 3                     NaN  ...                  NaN                     NaN
 4                     NaN  ...                  NaN                     NaN
 ...                   ...  ...                  ...                     ...
 3644                  NaN  ...                  NaN                     NaN
 3645                  NaN  ...                  NaN                     NaN
 3646                  NaN  ...                  NaN                     NaN
 3647                  NaN  ...                  NaN                     NaN
 3648                  NaN  ...                  NaN                     NaN

      substitution_replacement substitution_replacement_id  \
 0                         NaN                         NaN
 1                         NaN                         NaN
 2                         NaN                         NaN
 3                         NaN                         NaN
 4                         NaN                         NaN
 ...                       ...                         ...
 3644                      NaN                         NaN
 3645                      NaN                         NaN
 3646                      NaN                         NaN
 3647                      NaN                         NaN
 3648                      NaN                         NaN

                                                 tactics     team  team_id  \
 0     {'formation': 4231, 'lineup': [{'player': {'id...  England      768
 1     {'formation': 343, 'lineup': [{'player': {'id'...     Iran      797
 2                                                   NaN     Iran      797
 3                                                   NaN  England      768
 4                                                   NaN     Iran      797
 ...                                                 ...      ...      ...
 3644                                                NaN     Iran      797
 3645                                                NaN  England      768
 3646                                                NaN  England      768
 3647                                                NaN  England      768
 3648                                                NaN  England      768

          timestamp         type under_pressure
 0     00:00:00.000  Starting XI            NaN
 1     00:00:00.000  Starting XI            NaN
 2     00:00:00.000   Half Start            NaN
 3     00:00:00.000   Half Start            NaN
 4     00:00:00.000   Half Start            NaN
 ...            ...          ...            ...
 3644  00:58:05.758     Half End            NaN
 3645  00:04:37.860   Player Off            NaN
 3646  00:22:36.180   Player Off            NaN
 3647  00:05:00.526    Player On            NaN
 3648  00:24:21.979    Player On            NaN

 [3649 rows x 94 columns],
      50_50 ball_receipt_outcome ball_recovery_offensive  \
 0      NaN                  NaN                     NaN
 1      NaN                  NaN                     NaN
 2      NaN                  NaN                     NaN
 3      NaN                  NaN                     NaN
 4      NaN                  NaN                     NaN
 ...    ...                  ...                     ...
 4111   NaN                  NaN                     NaN
 4112   NaN                  NaN                     NaN
 4113   NaN                  NaN                     NaN
 4114   NaN                  NaN                     NaN
 4115   NaN                  NaN                     NaN

      ball_recovery_recovery_failure block_offensive carry_end_location  \
 0                               NaN             NaN                NaN
 1                               NaN             NaN                NaN
 2                               NaN             NaN                NaN
 3                               NaN             NaN                NaN
 4                               NaN             NaN                NaN
 ...                             ...             ...                ...
 4111                            NaN             NaN                NaN
 4112                            NaN             NaN                NaN
 4113                            NaN             NaN                NaN
 4114                            NaN             NaN                NaN
 4115                            NaN             NaN                NaN

      clearance_aerial_won clearance_body_part clearance_head  \
 0                     NaN                 NaN            NaN
 1                     NaN                 NaN            NaN
 2                     NaN                 NaN            NaN
 3                     NaN                 NaN            NaN
 4                     NaN                 NaN            NaN
 ...                   ...                 ...            ...
 4111                  NaN                 NaN            NaN
 4112                  NaN                 NaN            NaN
 4113                  NaN                 NaN            NaN
 4114                  NaN                 NaN            NaN
 4115                  NaN                 NaN            NaN

      clearance_left_foot  ... substitution_outcome substitution_outcome_id  \
 0                    NaN  ...                  NaN                     NaN
 1                    NaN  ...                  NaN                     NaN
 2                    NaN  ...                  NaN                     NaN
 3                    NaN  ...                  NaN                     NaN
 4                    NaN  ...                  NaN                     NaN
 ...                  ...  ...                  ...                     ...
 4111                 NaN  ...             Tactical                   103.0
 4112                 NaN  ...                  NaN                     NaN
 4113                 NaN  ...                  NaN                     NaN
 4114                 NaN  ...                  NaN                     NaN
 4115                 NaN  ...                  NaN                     NaN

      substitution_replacement substitution_replacement_id  \
 0                         NaN                         NaN
 1                         NaN                         NaN
 2                         NaN                         NaN
 3                         NaN                         NaN
 4                         NaN                         NaN
 ...                       ...                         ...
 4111              Lovro Majer                     28914.0
 4112                      NaN                         NaN
 4113                      NaN                         NaN
 4114                      NaN                         NaN
 4115                      NaN                         NaN

                                                 tactics     team team_id  \
 0     {'formation': 433, 'lineup': [{'player': {'id'...  Croatia     785
 1     {'formation': 4231, 'lineup': [{'player': {'id...  Belgium     782
 2                                                   NaN  Belgium     782
 3                                                   NaN  Croatia     785
 4                                                   NaN  Croatia     785
 ...                                                 ...      ...     ...
 4111                                                NaN  Croatia     785
 4112  {'formation': 4231, 'lineup': [{'player': {'id...  Belgium     782
 4113  {'formation': 4231, 'lineup': [{'player': {'id...  Belgium     782
 4114  {'formation': 4231, 'lineup': [{'player': {'id...  Belgium     782
 4115  {'formation': 4231, 'lineup': [{'player': {'id...  Belgium     782

          timestamp            type under_pressure
 0     00:00:00.000     Starting XI            NaN
 1     00:00:00.000     Starting XI            NaN
 2     00:00:00.000      Half Start            NaN
 3     00:00:00.000      Half Start            NaN
 4     00:00:00.000      Half Start            NaN
 ...            ...             ...            ...
 4111  00:45:54.476    Substitution            NaN
 4112  00:00:00.000  Tactical Shift            NaN
 4113  00:21:22.340  Tactical Shift            NaN
 4114  00:27:52.733  Tactical Shift            NaN
 4115  00:42:03.746  Tactical Shift            NaN

 [4116 rows x 93 columns],
      50_50 ball_receipt_outcome ball_recovery_recovery_failure  \
 0      NaN                  NaN                            NaN
 1      NaN                  NaN                            NaN
 2      NaN                  NaN                            NaN
 3      NaN                  NaN                            NaN
 4      NaN                  NaN                            NaN
 ...    ...                  ...                            ...
 3558   NaN                  NaN                            NaN
 3559   NaN                  NaN                            NaN
 3560   NaN                  NaN                            NaN
 3561   NaN                  NaN                            NaN
 3562   NaN                  NaN                            NaN

      block_offensive carry_end_location clearance_aerial_won  \
 0                NaN                NaN                  NaN
 1                NaN                NaN                  NaN
 2                NaN                NaN                  NaN
 3                NaN                NaN                  NaN
 4                NaN                NaN                  NaN
 ...              ...                ...                  ...
 3558             NaN                NaN                  NaN
 3559             NaN                NaN                  NaN
 3560             NaN                NaN                  NaN
 3561             NaN                NaN                  NaN
 3562             NaN                NaN                  NaN

      clearance_body_part clearance_head clearance_left_foot  \
 0                    NaN            NaN                 NaN
 1                    NaN            NaN                 NaN
 2                    NaN            NaN                 NaN
 3                    NaN            NaN                 NaN
 4                    NaN            NaN                 NaN
 ...                  ...            ...                 ...
 3558                 NaN            NaN                 NaN
 3559                 NaN            NaN                 NaN
 3560                 NaN            NaN                 NaN
 3561                 NaN            NaN                 NaN
 3562                 NaN            NaN                 NaN

      clearance_right_foot  ... substitution_outcome substitution_outcome_id  \
 0                     NaN  ...                  NaN                     NaN
 1                     NaN  ...                  NaN                     NaN
 2                     NaN  ...                  NaN                     NaN
 3                     NaN  ...                  NaN                     NaN
 4                     NaN  ...                  NaN                     NaN
 ...                   ...  ...                  ...                     ...
 3558                  NaN  ...                  NaN                     NaN
 3559                  NaN  ...                  NaN                     NaN
 3560                  NaN  ...                  NaN                     NaN
 3561                  NaN  ...                  NaN                     NaN
 3562                  NaN  ...                  NaN                     NaN

      substitution_replacement substitution_replacement_id  \
 0                         NaN                         NaN
 1                         NaN                         NaN
 2                         NaN                         NaN
 3                         NaN                         NaN
 4                         NaN                         NaN
 ...                       ...                         ...

In [21]:
kane = df[df['player'] == 'Harry Kane']

In [22]:
kane

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,shot_redirect,goalkeeper_punched_out,bad_behaviour_card,block_save_block,goalkeeper_shot_saved_off_target,shot_saved_off_target,goalkeeper_success_in_play,shot_follows_dribble,half_start_late_video_start,goalkeeper_lost_in_play
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN